# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformCLI@2
  displayName: Terraform init
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/acr'
    allowTelemetryCollection: false
- task: TerraformCLI@2
  displayName: Terraform plan
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/acr'
    environmentServiceName: 'aks-deploy'
    allowTelemetryCollection: false
